# Generated by Django 3.2.12 on 2022-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100, verbose_name='Hash of transaction:')),
                ('sender', models.CharField(max_length=50, verbose_name='Sender:')),
                ('receiver', models.CharField(max_length=50, verbose_name='Reciver:')),
                ('valueEth', models.CharField(max_length=50, verbose_name='Number of ETH:')),
                ('confirmation', models.CharField(max_length=50, verbose_name='Confirmation:')),
                ('exchangeName', models.CharField(max_length=50, verbose_name='Exchange place:')),
            ],
            options={
                'verbose_name': 'ethAdresses',
            },
        ),
    ]
