# Generated by Django 3.2.12 on 2022-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='confirmation',
            field=models.CharField(max_length=100, verbose_name='Confirmation:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='exchangeName',
            field=models.CharField(max_length=100, verbose_name='Exchange place:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='receiver',
            field=models.CharField(max_length=100, verbose_name='Reciver:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sender',
            field=models.CharField(max_length=100, verbose_name='Sender:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='valueEth',
            field=models.CharField(max_length=100, verbose_name='Number of ETH:'),
        ),
    ]
